sudo: false
language: node_js
node_js:
- stable
- '8'
script:
- npm install
- npm test
deploy:
  provider: npm
  email: dev.api@myunidays.com
  api_key:
    secure: EVGMwkaIRNNVvODcAZZvw/NW+J2la/wp5naojtKTZBdJwq2VahaF2+EPkUVYJoQuzp8X2Yk5Prnvl/PLepzo5qTp3EWI9M33XsezvqkHZ16mbQ4Pmt2ydHRakx5EKDVuOKhttRFNnKMUzc8LRbpJK4qeDXkMRnVhHrHhuPQM6cBhiqG/K6s2hGQdV3Q7ie+qvj9bTnALIIsqgF8OD9sb7LLrU12LVpqiKx2pv26opF4i+dgswIOg/FnGDhLycsuycIwi8BhAaJumTSt5NHK4nwKvhz3TWsx5YaqMzVfbt+LygirJubl61r/47cRqkSyfLG7T5rh/kMTGGDp2K58dQXiFVycIIdu+xJxwMZdPC0layAaW6oV39S3UXAeq0ltJipTgd/AXR6x679LcHTspTmhxiotVUFpqPN+oMNQFZTrC/f4rZe7R6CKtTJPL80hRwsofUq/xzYVKsZhlC9H91UzHJsV0Jgs8t2BMEynuVFvI2O1KHu9S0i2mBfH1w4R5QvO36kwAlE8BHigs14CEzUmTciioI2O/0UCJGI6Ox+UCcv/YeGLknnKkobCkz1aJUToDaFh8OioNAptuHOUqkCuG51utoDa+3mHY9s8DgvdR2EtOROiHjjIGciFuf3scLUjWmRaajkmhQYedOENYxg4z+n9RfDZjC/BthqAKm5s=
  on:
    branch: master
    node: stable
notifications:
  slack:
    secure: iQCts3qtlEmhQeX0zoZS9SCN45rxUciCRuZ5L5L0XLjQqez7MlmY9pB8JwLhXuyjqJORP7MJNfQk2SX+K3IOVNSDGcHH7E0UE9e82vZje0QrIrm3jluNMUvswG7ifwJUOpINTvDMbmUeRq1o3vPUQtaV4813DvFm2/cr7djPGOQOIp1jGA04JQ4nscAdwlJ3mcQ64ibWHTIagYCVji6souIEdMbdoxwvXjtTPtRyGtlkc/G1xA5FkoM6euzdNLq6unh2YEwLVliyJrbzJhcgp3YaCHV7Yn6TMXepQd3dkLpTgIhNBGMOcDeUCwDChmTF8p7+CDwQkjJswu9/G8JXU7djAAdIW8V/+PzKGNDV/U9dAHVlU9daCiyP8CcSjEaWO0rBx/r6x0fFLd5nkmopu4BfmL3UVEa6Z3xfoPVY1RS73uQYjhy02gmx0csTD+DBd5Xa1rn1Py0ot79zl7hjjoNxgi1vdnYlRtxDiWlp1sWQF9SrUnDb0i+mTKjZAh4XgOwMhJXDwvtdDZDIGhJC4Pf3IM76T+KgeFqjOqJTUs0QvY1ORTeHiVazbhf/eHM36RMG5e+MAnKHHj8+0saA1qBBNvMUoEUzb/C8ZV5t92rxx24YSvnMTm/txIUXXI7wRLmFS59FltBh4HjKn/ZeEA37OrMUq4DBCT0JK31hUvI=
    on_success: never
    on_failure: always
