sudo: false
language: node_js
node_js:
- stable
- '8'
script:
- npm install
- npm test
deploy:
  provider: npm
  email: dev.api@myunidays.com
  api_key:
    secure: ciSh+iJSF54cbspPda9Mto/cPNs2wQkV6ra1SGL9h0ZUQ0jQkDCY/j+MYP3FkFJSt2uCXsGXWp+v3yPWvSWTEF8wIcCgLOT3C20+uPkcf2fdNyOpYk/zJUjaIzNQ8qFrvA/vF+2kqpQk5Tv2fG1/rb+vjnPtUYapwKZtptms0bzi7foG42iH3HioWW/jP3ER5k9DzIaJnLvxuVvqdUW5yTTk1nvc1dOmxmejAB/NbIfAFtuzFU8z7vqb6EH4DugUbCGK76mg38wrDSVCY4IGpOm3qd0Vsg/7BOBVp35iBzM9cSZMQSM0XIgH5eOcMUiIk12eklPfva8n/kF/5p5wIw5UTlWedw8M7FXcqG5zi2FwaSlVaeZUsVXMyah01yjKadS+dF8hwyQw69Kkx3s/K0nH0gLziTmALRJBafU3UC3rfHpGK/Bd7x45MPieetBizPyaKW611kcbmEhVbY2mq1du4r15BIHEtBPlGTH+yxITMmCsBo/bwwbGEe3Q37w5yDLkFNiUgW81MMIv4ALNiq5H+9faQ7fdP0lj70eWgEIECLylEfL2725f6dyDOZa7wX44tfWcFjP2FQXuighe3Zbz0ThRbExOtmwzfalmnhsz53hFGEiTqYVJP8SgN6m8/0l8DOhB/yIfSxXB3v978qRJ3Yw6JPy2nMr3l2l10uQ=
  on:
    branch: master
    node: stable
notifications:
  slack:
    secure: iQCts3qtlEmhQeX0zoZS9SCN45rxUciCRuZ5L5L0XLjQqez7MlmY9pB8JwLhXuyjqJORP7MJNfQk2SX+K3IOVNSDGcHH7E0UE9e82vZje0QrIrm3jluNMUvswG7ifwJUOpINTvDMbmUeRq1o3vPUQtaV4813DvFm2/cr7djPGOQOIp1jGA04JQ4nscAdwlJ3mcQ64ibWHTIagYCVji6souIEdMbdoxwvXjtTPtRyGtlkc/G1xA5FkoM6euzdNLq6unh2YEwLVliyJrbzJhcgp3YaCHV7Yn6TMXepQd3dkLpTgIhNBGMOcDeUCwDChmTF8p7+CDwQkjJswu9/G8JXU7djAAdIW8V/+PzKGNDV/U9dAHVlU9daCiyP8CcSjEaWO0rBx/r6x0fFLd5nkmopu4BfmL3UVEa6Z3xfoPVY1RS73uQYjhy02gmx0csTD+DBd5Xa1rn1Py0ot79zl7hjjoNxgi1vdnYlRtxDiWlp1sWQF9SrUnDb0i+mTKjZAh4XgOwMhJXDwvtdDZDIGhJC4Pf3IM76T+KgeFqjOqJTUs0QvY1ORTeHiVazbhf/eHM36RMG5e+MAnKHHj8+0saA1qBBNvMUoEUzb/C8ZV5t92rxx24YSvnMTm/txIUXXI7wRLmFS59FltBh4HjKn/ZeEA37OrMUq4DBCT0JK31hUvI=
    on_success: never
    on_failure: always
