version: 1.0.{build}
   
init:
  - git config --global core.autocrlf true

skip_branch_with_pr: true

skip_tags: true

environment:
  matrix:
    - nodejs_version: '8'

install:
  - npm install
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
build_script:
  - npm pack

artifacts:
  - path: '**\*.tgz'
    name: npm
  
test_script:
  - npm test
 
on_failure:
  - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-fail-$(Get-Date -format dd_mm_yyyy_HH_mm_ss)"

for:
  - branches:
      only:
        - master
    on_success:
       - npm publish --access public
# all branches except master
  - branches:
      except:
        - master
    environment:
      matrix:
         - nodejs_version: '6'